config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'home/index'

  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'confirm', sign_up: 'new' },
             controllers: {
               registrations: 'registrations',
               sessions: 'sessions',
               confirmations: 'confirmations',
               passwords: 'passwords'
             }

  resource :users, only: [] do
    get :join_team, on: :member
  end

  # Saying resources :users do causes all routes for the team to be generated.
  # By saying only: [] it keeps only the routes specified in the do block to be generated.
  resources :teams, except: %i[destroy] do
    # Different route for inviting a user to the team.
    member do
      patch :invite
      put :invite
      get :summary
    end
    # Custom route for accepting user invites.
    resources :user_invites, only: [:destroy] do
      get :accept, on: :member
    end
    resources :user_requests, only: %i[create destroy] do
      get :accept, on: :member
    end
    resources :users, only: [] do
      delete :leave_team
      get :promote
    end
  end

  # game
  resource :game, only: %i[show] do
    get :completion_certificate_template
    get :privacy_notice
    get :summary
    get :terms_of_service
    resources :pages, only: %i[index show]
    resources :messages, only: [:index]
    resources :achievements, only: [:index]
    resources :divisions, only: [:index]
    resources :flags, only: [:index] # Prank route!
    resources :challenges, only: %i[show update]
    resources :teams, only: [] do
      resources :challenges, only: %i[show update]
    end
  end

  resources :file_submissions, only: [] do
    member do
      get :submitted_bundle
    end
  end

  root to: 'home#index'
end
# rubocop:enable Metrics/BlockLength

app/models/user.rb
# frozen_string_literal: true

# User model, uses devise to manage registrations. Each user has a team reference which is
# set to nil until they are added to a team.
class User < ApplicationRecord
  has_paper_trail only: %i[
    email
    team_id
    full_name
    affiliation
    year_in_school
    state
    compete_for_prizes
    admin
    current_sign_in_ip
  ]

  belongs_to :team, optional: true
  has_many :feed_items, dependent: :destroy
  has_many :user_invites, dependent: :destroy
  has_many :user_requests, dependent: :destroy
  has_many :submitted_flags, dependent: :destroy

  scope :interested_in_employment, -> { where(interested_in_employment: true) }

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :confirmable, :validatable

  # These are things we require user to have but do not require of admins.
  with_options unless: :admin? do
    after_create :link_to_invitations, :update_team
    after_update :update_team
    before_destroy :leave_team_before_delete, prepend: true
    before_save :clear_compete_for_prizes
    validates :email, uniqueness: true, presence: true
    validates :full_name, :affiliation, presence: true, length: { maximum: 255 }, obscenity: true
    validates :state, presence: true, if: -> { country.eql? 'US' }
    validates :year_in_school, inclusion: { in: [0, 9, 10, 11, 12, 13, 14, 15, 16] }, presence: true
    validates :age_requirement_accepted, presence: true
  end

  before_validation -> { self.state = nil }, unless: -> { country.eql? 'US' }

  before_create :skip_confirmation!, unless: -> { Settings.local_login.email_confirmation }

  def self.user_editable_keys
    # First line required fields, second line optional
    # Really just broken out into 2 lines to appease rubocop
    %i[
      full_name affiliation year_in_school state country age_requirement_accepted
      compete_for_prizes interested_in_employment gender age area_of_study
    ]
  end

  # Returns whether a user is currently on a team or not.
  def on_a_team?
    !team.nil?
  end

  def team_captain?
    if on_a_team?
      team.team_captain.eql? self
    else
      false
    end
  end

  def division
    return 'College' if year_in_school >= 13
    return 'Professional' if year_in_school.eql? 0
    return 'High School' if year_in_school <= 12
  end

  # A user can only promote another user if they are the team captain. The user that they
  # promote cannot be themselves.
  def can_promote?(user)
    (!eql? user) && (team.team_captain.eql? self)
  end

  # A user can only remove someone from a team if they are the team captain
  def can_remove?(user)
    (eql? user) || (team.team_captain.eql? self)
  end

  def update_messages_stamp
    update(messages_stamp: Time.now.utc)
  end

  def update_team
    team&.refresh_team_info
  end

  # generate cert for specific user
  def generate_certificate(rank)
    return nil unless on_a_team?

    output = Tempfile.new("#{id}_completion_certificate")
    rank ||= team.find_rank
    generate_certificate_helper(output, rank)

    output
  end

  private

  def generate_certificate_helper(output, rank)
    dimensions = [720, 540]
    CertModule::CompletionPdf.generate(output, page_size: dimensions) do |doc|
      doc.image doc.instance_variable_get(:@background), at: [0, dimensions[1]], fit: dimensions
      doc.bounding_box([55, 450], width: 640, height: 200) do
        Game.instance.generate_certificate_header doc
      end
      generate_certificate_body doc, rank
    end
  end

  def generate_certificate_body(doc, rank)
    doc.bounding_box([55, 200], width: 640, height: 200) do
      doc.font('Helvetica-Bold', size: 18) do
        doc.text(I18n.t('users.team_completion_cert_string',
                        full_name: full_name, team_name: team.team_name,
                        score: team.score, rank: rank, team_size: team.division.teams.size),
                 color: '005BA1', align: :center, leading: 4)
      end
    end
  end

  # If a user chooses to compete for prizes then they must be located in the US and be in school.
  # When a user is not in school the frontend sets the value to 0 and when they are located out
  # of the USA the state is set to NA.
  def clear_compete_for_prizes
    return if country.eql?('US') && !year_in_school.eql?(0)

    self.compete_for_prizes = false
    nil # http://apidock.com/rails/ActiveRecord/RecordNotSaved
  end

  # When a new user is created, check to see if the users email has been invited to any teams.
  def link_to_invitations
    UserInvite.where(email: email).find_each do |invite|
      invite.user = self
      invite.save
    end
  end

  # This should only be used when an account is being deleted, it allows the team to update internal information
  def leave_team_before_delete
    team&.users&.delete(self)
    team&.cleanup
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include ApplicationModule
  include UserModule
  include UserHelper

  before_action :user_logged_in?
  before_action :load_game, :load_message_count
  before_action :prevent_action_after_game, only: %i[join_team leave_team promote]
  before_action :check_removal_permissions, only: [:leave_team]
  before_action :check_if_user_on_team, only: [:join_team]
  before_action :check_promote_permissions, only: [:promote]
  before_action :fetch_user_team, :deny_team_in_top_ten, only: %i[leave_team promote]

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength
  def join_team
    @pending_invites = current_user.user_invites.pending
    @pending_requests = current_user.user_requests.pending
    (@filterrific = initialize_filterrific(
      Team, params[:filterrific],
      select_options: {
        state: state_enum,
        country: country_enum,
        division: Division.all.map { |d| [d.name, d.id] }
      }
    )) || return
    @teams = @filterrific.find.includes(:division).page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def leave_team
    is_current_captain = @team.team_captain&.id.eql?(params[:user_id].to_i)

    # Uses count to query database and get the most accurate count so user can't make a team empty
    if is_current_captain && @team.users.count > 1
      redirect_to @team, alert: I18n.t('teams.captain_must_promote')
    else
      @team.users.delete(params[:user_id])
      if current_user.team_captain? && !is_current_captain
        redirect_to @team, notice: I18n.t('teams.captain_removed_player')
      else
        @team.cleanup
        redirect_to join_team_users_path, notice: I18n.t('teams.player_removed_self')
      end
    end
  end

  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/MethodLength

  def promote
    if @team.promote(params[:user_id])
      redirect_to @team, notice: I18n.t('teams.promoted_captain')
    else
      redirect_to @team, alert: I18n.t('teams.cannot_promote_captain')
    end
  end

  private

  # Only allow the team captain or the current user to remove the current user from a team.
  def check_removal_permissions
    raise ActiveRecord::RecordNotFound unless team_captain? || current_user.id.eql?(params[:user_id].to_i)
  end

  def check_promote_permissions
    raise ActiveRecord::RecordNotFound unless team_captain?
  end

  def fetch_user_team
    @team = current_user.team
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  # All methods named appropriately to work with rails_admin select

  def year_in_school_enum
    [
      %w[9 9], %w[10 10], %w[11 11], %w[12 12],
      ['College - Freshman', '13'],
      ['College - Sophomore', '14'],
      ['College - Junior', '15'],
      ['College - Senior', '16'],
      ['Grad Student/Not in School', '0']
    ]
  end

  def country_enum
    countries = ISO3166::Country.all.map do |country|
      [country.iso_short_name, country.alpha2]
    end

    countries.sort.sort_by { |_name, code| code == 'US' ? 0 : 1 }
  end

  def state_enum
    ISO3166::Country.find_country_by_unofficial_names('United States').states.map { |key, struct| [struct.name, key] }
  end

  def required_for_update?(on_update_page)
    return 'control-label' if on_update_page

    'control-label-required'
  end
end

app/views/users/_join_team_invites_table.html.haml
%h3
  = t('users.join_team.pending_team_invites_header')
  %small= t('users.join_team.invites_header_desc')
%table.table.table-condensed.table-striped.table-hover
  %thead
  %tr
    %th= t('teams.invite.incomming_invites_table.team_name_header')
    %th= t('teams.invite.incomming_invites_table.invited_on_header')
    %th= t('teams.invite.incomming_invites_table.accept_reject_header')
  - @pending_invites.each do |current|
    %tbody
      %tr{:class=>'warning'}
        %td=current.team.team_name
        %td=current.created_at.strftime("%b %d %Y")
        %td
          = link_to accept_team_user_invite_path(current.team, current) do
            = fa_icon 'check'
          = link_to team_user_invite_path(current.team, current), method: :delete, data: {confirm: t('users.join_team.delete_invite_confirmation')} do
            = fa_icon 'remove'

app/views/users/_join_team_requests_table.html.haml
%h3
  = t('users.join_team.pending_team_requests_header')
  %small= t('users.join_team.requests_header_desc')
%table.table.table-condensed.table-striped.table-hover
  %thead
  %tr
    %th= t('teams.invite.requested_join_team_table.team_name_header')
    %th= t('teams.invite.requested_join_team_table.requested_on_header')
    %th= t('teams.invite.requested_join_team_table.cancel_request_header')
  - @pending_requests.each do |current|
    %tbody
      %tr{:class=>'warning'}
        %td=current.team.team_name
        %td=current.created_at.strftime("%b %d %Y")
        %td
          = link_to team_user_request_path(current.team, current), method: :delete, data: {confirm: t('users.join_team.delete_request_confirmation')} do
            = fa_icon 'remove'

app/views/users/join_team.html.haml
- content_for :header do
  = t('users.join_team.header')
- unless @pending_invites.empty?
  = render partial: 'users/join_team_invites_table'
- unless @pending_requests.empty?
  = render partial: 'users/join_team_requests_table'
%h3= t('users.join_team.search_for_team_header')

= form_for_filterrific @filterrific, html: { class: 'form_for_filterrific' } do |f|
  .card.card-body.bg-light
    .container
      .form-group.row
        .col-lg
          Team Name
          = f.text_field(                                                   |
              :filter_team_name,                                            |
              class: 'filterrific-periodically-observed form-control span3' |
            )                                                               |
        .col-lg
          Affiliation
          = f.text_field(                                                   |
              :filter_affiliation,                                          |
              class: 'filterrific-periodically-observed form-control span3' |
            )                                                               |
        .col-lg
          Country
          = f.select(                                 |
              :country,                               |
              @filterrific.select_options[:country],  |
              { :include_blank => '- Any -' },        |
              :class => "span2 form-control",         |
            )                                         |
        .col-lg#state
          State
          = f.select(                                 |
              :state,                              |
              @filterrific.select_options[:state],    |
              { :include_blank => '- Any -' },        |
              :class => "span2 form-control",         |
            )                                         |
        .col-lg
          Division
          = f.select(                                 |
              :division,                              |
              @filterrific.select_options[:division], |
              { :include_blank => '- Any -' },        |
              :class => "span3 form-control",         |
            )                                         |
        .span1
          = render_filterrific_spinner

= render(                                 |
  partial: 'teams/list',                  |
  locals: { teams: @teams }               |
)                                         |

app/views/users/join_team.js.haml
- js = escape_javascript(render(partial: 'teams/list', locals: { teams: @teams }))
$("#filterrific_results").html("#{js}");