config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'home/index'

  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'confirm', sign_up: 'new' },
             controllers: {
               registrations: 'registrations',
               sessions: 'sessions',
               confirmations: 'confirmations',
               passwords: 'passwords'
             }

  resource :users, only: [] do
    get :join_team, on: :member
  end

  # Saying resources :users do causes all routes for the team to be generated.
  # By saying only: [] it keeps only the routes specified in the do block to be generated.
  resources :teams, except: %i[destroy] do
    # Different route for inviting a user to the team.
    member do
      patch :invite
      put :invite
      get :summary
    end
    # Custom route for accepting user invites.
    resources :user_invites, only: [:destroy] do
      get :accept, on: :member
    end
    resources :user_requests, only: %i[create destroy] do
      get :accept, on: :member
    end
    resources :users, only: [] do
      delete :leave_team
      get :promote
    end
  end

  # game
  resource :game, only: %i[show] do
    get :completion_certificate_template
    get :privacy_notice
    get :summary
    get :terms_of_service
    resources :pages, only: %i[index show]
    resources :messages, only: [:index]
    resources :achievements, only: [:index]
    resources :divisions, only: [:index]
    resources :flags, only: [:index] # Prank route!
    resources :challenges, only: %i[show update]
    resources :teams, only: [] do
      resources :challenges, only: %i[show update]
    end
  end

  resources :file_submissions, only: [] do
    member do
      get :submitted_bundle
    end
  end

  root to: 'home#index'
end
# rubocop:enable Metrics/BlockLength

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for the homepage. Since there is not much logic on the homepage this controller is
# rather empty.
class HomeController < ApplicationController
  before_action :load_game, :load_message_count

  def index; end
end

app/views/home/index.html.haml
- content_for :header do
  = @game&.title

.container
  .catchphrase
    - if @game.before_competition?
      %h2= t('home.index.catchprase.before_completion')
    - elsif @game.open?
      %h2= t('home.index.catchprase.game_open')
    - else
      %h2= t('home.index.catchprase.game_completed')
  .maincontent.row-fluid.indent-40px-left
    %p
      %b
        %u= t('home.index.description')
    = sanitize(Kramdown::Document.new(@game&.description).to_html)
    %p
      %b
        %u= t('home.index.when_to_compete')
    %p= t('home.index.when_to_compete_info', start_time: view_time_format(@game.start), end_time: view_time_format(@game.stop))
    - unless @game&.contact_url.blank?
      %p
        %b
          %u= t('home.index.stuck')
      %p= raw(t('home.index.stuck_info', contact_url: link_to(t('home.index.contact_us'), @game.contact_url)))
  - unless @game.after_competition?
    - if user_signed_in?
      .btn-toolbar
        .pagination-centered.mx-auto
          - if current_user.on_a_team?
            .btn-group
              = link_to t('home.index.join_team'), team_path(current_user.team_id), :class => "btn btn-large btn-primary"
          - else
            .btn-group
              = link_to t('home.index.join_team'), join_team_users_path, :class => "btn btn-large btn-primary"
            .btn-group
              = link_to t('home.index.create_team'), new_team_path, :class => "btn btn-large btn-primary"
    - elsif @game.registration_enabled
      .btn-toolbar
        .pagination-centered.mx-auto
          .btn-group
            = link_to t('home.index.register'), new_user_registration_path, :class => "btn btn-large btn-primary"