config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'home/index'

  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'confirm', sign_up: 'new' },
             controllers: {
               registrations: 'registrations',
               sessions: 'sessions',
               confirmations: 'confirmations',
               passwords: 'passwords'
             }

  resource :users, only: [] do
    get :join_team, on: :member
  end

  # Saying resources :users do causes all routes for the team to be generated.
  # By saying only: [] it keeps only the routes specified in the do block to be generated.
  resources :teams, except: %i[destroy] do
    # Different route for inviting a user to the team.
    member do
      patch :invite
      put :invite
      get :summary
    end
    # Custom route for accepting user invites.
    resources :user_invites, only: [:destroy] do
      get :accept, on: :member
    end
    resources :user_requests, only: %i[create destroy] do
      get :accept, on: :member
    end
    resources :users, only: [] do
      delete :leave_team
      get :promote
    end
  end

  # game
  resource :game, only: %i[show] do
    get :completion_certificate_template
    get :privacy_notice
    get :summary
    get :terms_of_service
    resources :pages, only: %i[index show]
    resources :messages, only: [:index]
    resources :achievements, only: [:index]
    resources :divisions, only: [:index]
    resources :flags, only: [:index] # Prank route!
    resources :challenges, only: %i[show update]
    resources :teams, only: [] do
      resources :challenges, only: %i[show update]
    end
  end

  resources :file_submissions, only: [] do
    member do
      get :submitted_bundle
    end
  end

  root to: 'home#index'
end
# rubocop:enable Metrics/BlockLength

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  validates :title, :start, :stop, :contact_email, :description, presence: true

  validate :instance_is_singleton, :order_of_start_and_stop_date

  mount_uploader :completion_certificate_template, CompletionCertificateTemplateUploader

  validates :completion_certificate_template, presence: true, if: :enable_completion_certificates?

  with_options dependent: :destroy do
    has_many :messages
    has_many :categories, dependent: :destroy
    has_many :pentest_challenges, dependent: :destroy
    has_many :defense_flags, through: :pentest_challenges
    has_many :standard_challenges, dependent: :destroy
    has_many :challenges, inverse_of: :game, foreign_key: 'game_id'
    has_many :divisions, dependent: :destroy
    has_many :teams, through: :divisions
    has_many :users, through: :teams
    has_many :feed_items, through: :divisions
    has_many :achievements, through: :divisions
    has_many :standard_solved_challenges, through: :divisions
    has_many :pentest_solved_challenges, through: :divisions
    has_many :solved_challenges, through: :divisions
    has_many :pages
  end

  enum board_layout: { jeopardy: 0, teams_x_challenges: 1, multiple_categories: 2, title_and_description: 3 }

  after_commit { Rails.cache.delete('game_instance') }

  def self.instance
    Rails.cache.fetch('game_instance') { all.first }
  end

  def instance_is_singleton
    singleton = Game.all.first
    errors.add(:base, I18n.t('game.too_many')) if self != singleton && !singleton.nil?
  end

  def order_of_start_and_stop_date
    errors.add(:base, I18n.t('game.date_mismatch')) unless start < stop
  end

  def open?
    time = Time.now.utc
    (start < time && time < stop)
  end

  def before_competition?
    Time.now.utc < start
  end

  def after_competition?
    Time.now.utc > stop
  end

  # As the game progresses, this returns a reasonable grouping for the different graphs in the application.
  # One such graph is on the Team Summary page and the other is the Game Summary
  def graph_group_method
    ((defense_end - start) / 1.day).days < 1.week ? :hour : :day
  end

  def categories_with_standard_challenges
    standard_challenges&.group_by(&:category_ids)&.sort_by { |categories, _| -categories.length }&.to_h
  end

  # This method returns either the current time in UTC or end of the game if the game is over.
  # The end of the defense time is either the end of the game or current time if we are during the game.
  # This is used to show the defensive points in a more sliding manner, instead of just showing
  # all of the potential points a team can earn for defense, it only shows up to the current time.
  def defense_end
    open? ? Time.now.utc : stop
  end

  def remind_all
    User.all.find_each do |usr|
      UserMailer.competition_reminder(usr).deliver_later
    end
  end

  # generates the top of the certificate when given a Prawn Document
  def generate_certificate_header(doc)
    doc.font('Helvetica', size: 28, style: :bold) do
      doc.text title.to_s, color: '005BA1', size: 28, align: :center, leading: 8
      doc.text "#{start.day}-#{stop.day} #{I18n.t('date.month_names')[start.month]} #{start.year}",
               color: '005BA1', align: :center, size: 20
    end
  end

  # Fetch every teams name and current score to provide JSON feed of team rankings
  def all_teams_information
    results = divisions.collect(&:ordered_teams_with_rank).flatten
    results.collect { |team| { pos: team.rank, team: team.team_name, score: team.current_score } }
  end

  def max_category_size
    categories_with_standard_challenges.values.map(&:length).max || 0
  end

  def teams_associated_with_flags_and_pentest_challenges
    teams.map do |team|
      team_challenge_flags = pentest_challenges.map do |challenge|
        matched_flag = defense_flags.to_a.find do |flag|
          flag.team_id.eql?(team.id) && flag.challenge_id.eql?(challenge.id)
        end
        { flag: matched_flag, challenge: challenge }
      end
      [team, team_challenge_flags]
    end
  end
end

app/models/jeopardy_game.rb
# frozen_string_literal: true

class JeopardyGame < Game
  with_options dependent: :destroy do
    has_many :categories, foreign_key: :game_id, inverse_of: :game
    has_many :challenges, through: :categories
    has_many :divisions, foreign_key: 'game_id', class_name: 'PointDivision', inverse_of: :game
    has_many :teams, through: :divisions
    has_many :users, through: :teams
    has_many :feed_items, through: :divisions
    has_many :achievements, through: :divisions
    has_many :solved_challenges, class_name: 'PointSolvedChallenge', through: :divisions
  end

  alias load_categories_or_teams categories
end

app/controllers/games_controller.rb
# frozen_string_literal: true

require 'zip'

class GamesController < ApplicationController
  include ApplicationModule

  before_action :load_game, only: %i[terms_of_service privacy_notice]

  before_action only: %i[completion_certificate_template] do
    load_game(:users)
    deny_if_not_admin
  end
  before_action only: %i[summary] do
    load_game(divisions: :teams)
    load_users_and_divisions
    load_game_graph_data
  end
  before_action only: %i[show] do
    deny_users_to_non_html_formats
    load_game(
      :categories, :teams,
      { standard_challenges: :solved_challenges },
      { pentest_challenges: :solved_challenges },
      flags: { solved_challenges: :team }
    )
  end
  before_action :filter_access_before_game_open
  before_action :load_message_count

  def terms_of_service; end

  def privacy_notice; end

  def show
    prepare_pentest_challenge_table # Always show PentestChallenges, no matter the Gameboard type
    prepare_standard_challenge_table
    respond_to do |format|
      format.html
      format.markdown do
        render_to_string :show
      end
    end
  end

  def summary
    respond_to do |format|
      format.html
      format.json { render json: { standings: @game.all_teams_information } }
    end
  end

  def completion_certificate_template
    download_file(@game.completion_certificate_template, @game.title)
  end

  def load_users_and_divisions
    @divisions = @game.divisions
    signed_in_not_admin = !current_user&.admin?
    @active_division = signed_in_not_admin && current_user&.team ? current_user&.team&.division : @divisions.first
  end

  def load_game_graph_data
    @group_method = @game.graph_group_method
    @flags_per_hour = SubmittedFlag.group_by_period(@group_method, :created_at).count
    prepare_line_chart_data
  end

  def prepare_line_chart_data
    @line_chart_data = [
      {
        name: I18n.t('game.summary.flag_submissions_graph.flags_submitted'), data: @flags_per_hour
      },
      {
        name: I18n.t('game.summary.flag_submissions_graph.challenges_solved'),
        data: FeedItem.solved_challenges.group_by_period(@group_method, :created_at).count
      }
    ]
  end

  def deny_users_to_non_html_formats
    deny_if_not_admin unless request.format.html?
  end

  private

  def prepare_standard_challenge_table
    # What information we need depends on the game mode we are in, however
    # we will always need a list of challenges
    if @game.jeopardy? || @game.title_and_description?
      prepare_jeopardy_or_title_and_description_board
    else
      @standard_challenges = @game&.standard_challenges
      ActiveRecord::Precounter.new(@standard_challenges).precount(:solved_challenges)
      prepare_teams_x_challenges_table if @game.teams_x_challenges?
    end
  end

  def prepare_teams_x_challenges_table
    @headings = [
      Struct.new(:name).new(I18n.t('game.summary.challenge_table.teams_header')), @standard_challenges
    ].flatten
    @teams = @game&.teams
  end

  def prepare_jeopardy_or_title_and_description_board
    @standard_challenges = @game&.categories_with_standard_challenges
    @categories = @game.categories
    @category_ids = @standard_challenges.keys
  end

  def prepare_pentest_challenge_table
    @pentest_challenges = @game&.pentest_challenges
    ActiveRecord::Precounter.new(@pentest_challenges).precount(:solved_challenges)
    @pentest_table_heading = [
      Struct.new(:name).new(I18n.t('game.summary.challenge_table.teams_header')), @game&.pentest_challenges
    ].flatten
    @teams_with_assoc = @game.teams_associated_with_flags_and_pentest_challenges
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
  def heading_width(headings)
    1.0 / headings.size.to_f * 100.0
  end

  def cell_background_color(team)
    return '' unless team.eql? current_user&.team

    'background-color: #F0F0F0;'
  end

  def challenge_colors(challenge, defense_team = nil)
    return %w[inherit inherit] unless challenge.respond_to?('open?')
    return ['#999999', '#000'] if own_team_challenge?(defense_team)

    challenge_color_for_other_team(challenge)
  end

  def challenge_text_for_team_for(challenge, team)
    if current_user&.team.eql?(team) && challenge.open? && challenge.can_be_solved_by(team)
      I18n.t('challenges.solve_state.click_to_solve')
    elsif !challenge.can_be_solved_by(team)
      I18n.t('challenges.solve_state.solved')
    else
      I18n.t('challenges.solve_state.unavailable_solve_state')
    end
  end

  # rubocop:disable Metrics/MethodLength
  def challenge_color_for_other_team(challenge)
    if challenge.force_closed?
      ['#800000', '#eee']
    elsif challenge.get_solved_challenge_for(current_user&.team)
      ['#00abca', '#eee']
    elsif challenge.solved?(2)
      ['#00cc00', '#444']
    elsif challenge.solved?(1)
      ['#009900', '#eee']
    elsif challenge.open?
      ['#006600', '#fff']
    else
      ['#999999', '#eee']
    end
  end
  # rubocop:enable Metrics/MethodLength

  def own_team_challenge?(defense_team)
    defense_team&.eql?(current_user&.team)
  end
end

app/views/games/_divisions.html.haml
- if divisions.size > 1
  .panel.panel-default
    -# Generate tabs for each division with a name
    %ul.nav.nav-tabs#summaryTabs
      - divisions.each do |d|
        %li{ :class => ('active' if active_division.eql? d) }
          = link_to "#{d.name}", "#division-#{d.id}-tab", "data-toggle"=>"tab", :class => 'nav-link text-dark'
    .tab-content
      - divisions.each do |d|
        .tab-pane{ :class => ('active' if active_division.eql? d), :id => "division-#{d.id}-tab" }
          = render partial: "games/team_list", locals: { teams: d.ordered_teams}
- else
  .container-fluid
    = render partial: "games/team_list", locals: { teams: divisions.first&.ordered_teams}

app/views/games/_jeopardy_game_table.html.haml
%thead
  %tr
    - @headings.each do |category|
      %th{ :style => "text-align:center;width:#{heading_width(@headings)}%;" }=category.name
%tbody
  - @table_rows.times do |row|
    %tr
      - @headings.size.times do |column_num|
        - if row < @headings[column_num].challenges.size
          = render partial: 'point_challenge',
            locals: { challenge: @headings[column_num].challenges[row], defense_team: nil }
        - else
          %td &nbsp;

app/views/games/_jeopardy_table.html.haml
%table.table.table-bordered.table-bolded.table-hover#jeopardy-table
  %thead
    %tr
      - @category_ids.each do |category|
        %th.text-center{ style: "width:#{heading_width(@category_ids)}%;" }=category_ids_to_names(category, @categories)
  %tbody
    - @game.max_category_size.times do |row|
      %tr
        - @category_ids.each do |category|
          - if row < @standard_challenges[category].size
            = render partial: 'standard_challenge',
              locals: { challenge: @standard_challenges[category][row] }
          - else
            %td &nbsp;

app/views/games/_legend.html.haml
%h3= t('game.legend.legend_name')
%blockquote.blockquote#legend
  %p#legendContent{style: "font-size: 1rem;"}
    %b{style: "color:#006600;"}
      = t('game.legend.dark_green')
    = t('game.legend.dark_green_desc')
    %br/
    %b{style: "color:#009900;"}
      = t('game.legend.green')
    = t('game.legend.green_desc')
    %br/
    %b{style: "color:#00cc00;"}
      = t('game.legend.light_green')
    = t('game.legend.light_green_desc')
    %br/
    %b{style: "color:#00abca;"}
      = t('game.legend.blue')
    = t('game.legend.blue_desc')
    %br/
    %b{style: "color:#999999;"}
      = t('game.legend.gray')
    = t('game.legend.gray_desc')
    %br/
    %b{style: "color:#800000;"}
      = t('game.legend.red')
    = t('game.legend.red_desc')

app/views/games/_multiple_categories_table.html.haml
%ul.thumbnails#multiple-categories
  - @standard_challenges.each do |challenge|
    %li.span3.multi-category-challenge
      - colors = challenge_colors(challenge)
      .thumbnail{style: "background-color: #{colors[0]}; color: #{colors[1]}"}
        .text-center
          %strong= challenge.name
          .score
            .badge.badge-inverse= challenge.display_point_value(current_user&.team)
          .categories
            - challenge.categories.each do |category|
              .label.label-lg.label-important=category.name
        = always_link_to_if_admin(challenge.open?, "", game_challenge_path(challenge), {style: 'display: none;'})

app/views/games/_standard_challenge.html.haml
%td.text-center{ style: "color: #{challenge_colors(challenge)[0]}" }= always_link_to_if_admin(challenge.open?, challenge.display_point_value(current_user&.team), game_challenge_path(challenge), style: "color:inherit;")

app/views/games/_team_list.html.haml
- if teams.nil? or teams.size.eql? 0
  %h4.zero-items-text= t('teams.summary.zero_teams_text')
- else
  - max = 0
  %table.table.table-bordered.table-striped.table-hover
    %thead
      %tr
        %th{ :style => "width:50px;" } #
        %th=t('game.team_list.team_name') # The team's name
        %th{ :style => "width:100px;" }= t('game.team_list.team_achievements') # The team's achievements
        %th{ :style => "width:100px;" }= t('game.team_list.team_points') # The number of points the team has
        %th{ :style => "width:50%;" }
      / Get the first teams score and use that as the full score bar
      - max_score = teams.first.current_score
      / We pass in starting_rank here to start the list at the proper index
      = render partial: 'games/team_list_tbody', locals: { teams: teams.slice(0..5), starting_rank: 1, max_score: max_score }
      / This part of the list is hidden until the user clicks the 'Show/Hide Teams' button below
      = render partial: 'games/team_list_tbody', locals: { |
               teams: teams.slice(6..),                    |
               starting_rank: 7,                           |
               max_score: max_score,                       |
               tbody_id: 'hiddenUntilToggle',              |
               tbody_class: 'd-none'                       |
        }                                                  |
    - if teams.count > 5
      %tr
        %td{align: 'center', colspan: '5', style: 'text-align: center;'}
          = link_to t('game.team_list.team_show_hide_btn'), "#", :class => "toggler"

app/views/games/_team_list_tbody.html.haml
- tbody_class ||= ''
- tbody_id ||= ''

%tbody{class: tbody_class, id: tbody_id}
  - teams&.each&.with_index(starting_rank) do |t, i|
    - score = t.current_score
    - percent = score.to_f / max_score.to_f * 100.0
    %tr
      %td= i
      %td.break-word= link_to display_name(t), summary_team_path(t)
      %td= t.achievements.size
      %td= score
      %td
        .progress{ :style => "margin:0; height:20px;" }
          .progress-bar{ :style => "width:#{percent}%;" }

app/views/games/_teams_x_challenges_table.html.haml
%table.table.table-bordered.table-bolded.table-hover#teams-x-challenges-table
  %thead
    %tr
      - @headings.each do |challenge|
        %th.text-center{ style: "width:#{heading_width(@headings)}%; color: #{challenge_colors(challenge)[0]}" }= challenge.name
  %tbody
    - @teams.each do |team|
      %tr
        %td.text-center.break-word= link_to(display_name(team), summary_team_path(team), style: "color:inherit;")
        - @standard_challenges.each do |challenge|
          %td.text-center
            = always_link_to_if_admin(challenge.open? && current_user&.team.eql?(team), challenge_text_for_team_for(challenge, team), game_challenge_path(challenge), style: "color:inherit;")

app/views/games/_title_and_description_table.html.haml
- @category_ids.each do |category|
  %h1=category_ids_to_names(category, @categories)
  - @standard_challenges[category].each do |challenge|
    .row
      .span12
        %h3{style: "color: #{challenge_colors(challenge)[0]}"}= challenge.name
        = challenge.description
        .solve{style: 'padding-top: 10px;'}
          = always_link_to_if_admin(challenge.open?, t('game.admin_view_submission_page'), game_challenge_path(challenge))
    %hr/

app/views/games/privacy_notice.html.haml
- content_for :header do
  = t('application.privacy.privacy_notice')

- if @game&.privacy_notice.blank?
  = t('application.privacy.no_notice')
- else
  = sanitize(Kramdown::Document.new(@game&.privacy_notice).to_html)

app/views/games/show.html.haml
- content_for :header do
  = @game.title

- if @pentest_challenges.size == 0 && @standard_challenges.size == 0
  %h4.zero-items-text= t('game.show.no_challenges')
- else
  -# Render based on the user selected gameboard layout
  #challengeTable= render partial: "games/#{@game.board_layout}_table"
  - unless @pentest_challenges.empty?
    %hr
    -# Always render PentestChallenges. This provides us with the ability to
    -# have Attack/Defend games with Generic challenge types on top
    = render partial: 'games/pentest_game_table'
= render partial: 'games/legend'

app/views/games/show.markdown.haml
= @game.title
= '=' * @game.title.length

- @standard_challenges.group_by(&:categories).each do |categories, challenges|
  - category_names = category_names(categories)
  = "\n\#\#\# #{category_names}\n"
  %table
    %tr
      %th= t('game.show_markdown.markdown_title')
      %th= t('game.show_markdown.markdown_value')
      %th= t('game.show_markdown.markdown_repository')
      %th= t('game.show_markdown.markdown_description')
    - challenges.each do |challenge|
      %tr
        %td= challenge.name
        %td= challenge.point_value
        %td
          %a{:href => "https://\<URL\>/\<YEAR\>-#{category_names}-#{challenge.point_value}"}
            = "\<YEAR\>-#{category_names}-#{challenge.point_value}"
        %td= challenge.description

- if @pentest_challenges
  = "\n\#\#\# #{I18n.t('game.attack_defend_challenges')}\n"
  %table
    %tr
      %th= t('game.show_markdown.markdown_title')
      %th= t('game.show_markdown.markdown_repository')
      %th= t('game.show_markdown.markdown_description')
    - @pentest_challenges.each do |challenge|
      %tr
        %td= challenge.name
        %td
          %a{:href => "https://\<URL\>/\<YEAR\>-#{challenge.name}"}
            = "\<YEAR\>-#{challenge.name}"
        %td= challenge.description

app/views/games/terms_of_service.html.haml
- content_for :header do
  = t('application.terms_of_use.terms_of_service')

- if @game&.terms_of_service.blank?
  = t('game.no_terms_of_service')
- else
  = sanitize(Kramdown::Document.new(@game&.terms_of_service).to_html)