config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'home/index'

  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'confirm', sign_up: 'new' },
             controllers: {
               registrations: 'registrations',
               sessions: 'sessions',
               confirmations: 'confirmations',
               passwords: 'passwords'
             }

  resource :users, only: [] do
    get :join_team, on: :member
  end

  # Saying resources :users do causes all routes for the team to be generated.
  # By saying only: [] it keeps only the routes specified in the do block to be generated.
  resources :teams, except: %i[destroy] do
    # Different route for inviting a user to the team.
    member do
      patch :invite
      put :invite
      get :summary
    end
    # Custom route for accepting user invites.
    resources :user_invites, only: [:destroy] do
      get :accept, on: :member
    end
    resources :user_requests, only: %i[create destroy] do
      get :accept, on: :member
    end
    resources :users, only: [] do
      delete :leave_team
      get :promote
    end
  end

  # game
  resource :game, only: %i[show] do
    get :completion_certificate_template
    get :privacy_notice
    get :summary
    get :terms_of_service
    resources :pages, only: %i[index show]
    resources :messages, only: [:index]
    resources :achievements, only: [:index]
    resources :divisions, only: [:index]
    resources :flags, only: [:index] # Prank route!
    resources :challenges, only: %i[show update]
    resources :teams, only: [] do
      resources :challenges, only: %i[show update]
    end
  end

  resources :file_submissions, only: [] do
    member do
      get :submitted_bundle
    end
  end

  root to: 'home#index'
end
# rubocop:enable Metrics/BlockLength

app/views/layouts/_countdown.html.haml
.pull-right#clock
  %h4
    #time_remaining{'data-endtime' => endTime.to_f * 1000}

app/views/layouts/_dropdown.html.haml
%li.nav-item.dropdown
  - if user_signed_in?
    %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :style => "color: #fff",:href => "#", :role => "button"}
      = greeting_for_dropdown(current_user)
    .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
      - if current_user.admin?
        %a.dropdown-item{:href => rails_admin_path}= t('application.admin.dashboard')
        .dropdown-divider
        %a.dropdown-item{:href => rails_admin.new_path("message")}= t('application.admin.post_message')
        %a.dropdown-item{:href => rails_admin.index_path("submitted_flag")}= t('application.admin.view_submitted_flags')
        %a.dropdown-item{:href => rails_admin.index_path("achievement")}= t('application.admin.award_achievement')
        %a.dropdown-item{:href => rails_admin.index_path("score_adjustment")}= t('application.admin.create_score_adjustment')
        - if content_for?(:admin_menu)
          .dropdown-divider
            = yield :admin_menu
        .dropdown-divider
      - elsif current_user.on_a_team?
        %a.dropdown-item{:href => team_path(current_user.team_id)}= t('home.index.view_team')
        - if current_user.team_captain?
          %a.dropdown-item{:href => edit_team_path(current_user.team_id)}= t('home.index.edit_team')
        .dropdown-divider
      - else
        %a.dropdown-item{:href => join_team_users_path}= t('home.index.join_team')
        %a.dropdown-item{:href => new_team_path}= t('home.index.create_team')
        .dropdown-divider
      %a.dropdown-item{:href => edit_user_registration_path}= t('application.edit_account')
      %a.dropdown-item{:href => destroy_user_session_path, "data-method" => :delete}= t('application.log_out')
  - else
    - unless @game.nil?
      %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :style => "color: #fff",:href => "#", :role => "button"}
        - if @game.registration_enabled
          = t('home.index.login_or_register')
        - else
          = t('home.index.login')
      .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
        %a.dropdown-item{:href => new_user_session_path}= t('application.log_in')
        - if @game.registration_enabled
          .dropdown-divider
          %a.dropdown-item{:href => new_user_registration_path}= t('home.index.register')

app/views/layouts/_flash_anchor.html.haml
- if !flash[:notice].blank?
  .alert.alert-success
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    = notice
- if !flash[:alert].blank?
  .alert.alert-danger
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    - if alert.is_a?(Enumerable)
      = amount_of_errors(alert)
      = list_of(alert) do |a|
        = a
    - else
      = alert

app/views/layouts/_footer.html.haml
.container
  .row-fluid
    %p.float-right
      %a{:href => "#"}
        = t('home.index.back_to_top')
    %p
      = "#{sanitize(@game.footer)} |" unless @game&.footer.blank?
      = link_to t('application.terms_of_use.terms_of_service'), terms_of_service_game_path
      |
      = link_to t('application.privacy.privacy_notice'), privacy_notice_game_path
    = t('application.open_source_statement_html', href: link_to(t('application.open_source_link_text'), t('application.github_link')))

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "/"}= organization_for_navbar(@game)
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse.justify-content-between
    %ul.navbar-nav
      %li.nav-item
        %a.nav-link{:href => game_path, :class => active_navbar?(game_path)}= t('application.navbar.challenges')
      %li.nav-item
        %a.nav-link{:href => game_messages_path, :class => active_navbar?(game_messages_path)}
          = t('application.navbar.messages')
          %span.badge.badge-pill.badge-info= unread_messages(@unread_message_count)
      %li.nav-item
        %a.nav-link{:href => game_achievements_path, :class => active_navbar?(game_achievements_path)}= t('application.navbar.achievements')
      %li.nav-item
        %a.nav-link{:href => summary_game_path, :class => active_navbar?(summary_game_path)}= t('application.navbar.summary')
      - unless @game.nil?
        - unless @game.contact_url.nil?
          %li.nav-item
            %a.nav-link{:href => @game.contact_url}= t('application.navbar.contact')
    %ul.nav.navbar-nav
      = render partial: 'layouts/dropdown'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= @game&.title
    = csp_meta_tag
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", nonce: true
    = csrf_meta_tags
  %body
    = render partial: 'layouts/navbar'
    %header#subpage.jumbotron.masthead
      .container
        %h1
          = yield :header
          - if @game&.open?
            = render partial: 'layouts/countdown', locals: { endTime: @game.stop }
        %p
          = yield :subheading
    .colored-divider
    .container
      = render partial: 'layouts/flash_anchor'
    .container
      = yield
  %footer#page-footer.card.card-body.bg-light.footer
    = render partial: 'layouts/footer'